import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import fileUpload from "express-fileupload";
import database from "./connectDB.js";
import { errorHandler } from "./middleware/errorMiddleware.js";
import userRoutes from "./routes/userRoutes.js";
import kycRouter from "./routes/kycRoutes.js";
import fetchRouter from "./routes/fetchRoutes.js";
import walletRouter from "./routes/walletRoutes.js";
import { profileRouter } from "./routes/profileRouter.js";
import { prospectOfferRouter } from "./routes/prospectOfferRouters.js";
import { sponsorOfferRouer } from "./routes/sponsorOfferRouters.js";
const app = express();
dotenv.config();
database();
app.use(fileUpload());
app.use(express.json());
app.use(cors());
app.use("/", fetchRouter);
app.use("/api/user", userRoutes);
app.use("/api/kyc", kycRouter);
app.use("/api/wallet", walletRouter);
app.use("/api/profile", profileRouter);
app.use(prospectOfferRouter);
app.use(sponsorOfferRouer);
app.use(errorHandler);
export default app;
